# Generated by Django 3.1.2 on 2020-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='feedback',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
